### ISSUE TITLE
Error on Layout Rebuild from Floating-Objects

### ISSUE THREAD

**Issue by JanKupke** [chandramouleswaran/Wide#12]
Load a Text document into the Program and do float it out. After this closes the Main-Application, if you restart it and if you want to drop it back, you will see the error. because you have build two layers with the same id. On trying to close one of them will be rise an fatal error.

**Comment by chandramouleswaran** [comment]
Fixed in #13

**Comment by chandramouleswaran** [comment]
Sorry - this took so long :) Had been hibernating for sometime.
