### ISSUE TITLE
Wide-MD with .net 4.5.1

### ISSUE THREAD

**Issue by ghost** [chandramouleswaran/Wide#58]
Have u tried compile Wide-MD application with .net 4.5.1?
Does it work? :)

**Comment by chandramouleswaran** [comment]
Yes - it does work. Wide does not use any 4.5.1 features yet. Do you have any other suggestions for the framework or any cool ideas which needs to be implemented?

I was thinking of a Quick search option similar to visual studio as the next step.

**Comment by ghost** [comment]
- a quicksearch would be nice.

i would like to see more components like:
- project/file explorer (didnt find a good one till now)
- toolbox (have to look more deeply at yours in your other application  :))
- node/graph editor (something like that from gemini)

i am planning to use this framework (or somthing with Caliburn.Micro, MvvmLight) at work. the isolated shell is to big. for a small tool it needs a 200mb runtime O.o. and i cant realy find a documentation for it. and its not opensource. :)

generally it could be optimised in some points. e.g. better general theme support.
better tool positions.
more flexible toolbars. all have to be loaded at start......
tried to move the toolbar creation in the add method. it works but not for the menuitems in the toolbar ...

there are much things that could be done -_-

**Comment by ghost** [comment]
btw https://compositewpf.codeplex.com/releases/view/117297
Prism 4.2 for .NET 4.5

**Comment by joazlazer** [comment]
What file explorer were you talking about? I am trying to implement one and I am getting drowned in all the infrastructure I need to make. MVVM makes the simplest things complicated.

**Comment by ghost** [comment]
a projectexplorer for project/file/object handling :)

**Comment by joazlazer** [comment]
Uugh I am trying the same. It proves a lot harder than I thought, especially with refreshing the tree view.
