### ISSUE TITLE
Add functionality to permit replacing Unity with IoC container of choice?

### ISSUE THREAD

**Issue by mmisztal1980** [chandramouleswaran/Wide#6]
Hi there,

I'm very impressed with your work, if possible I'd like to recommend that you add functionality similar to ASP.NET MVC IDependencyResolver - so that people can hook up a container of their choice.

Other then that , great work - very impressive.

**Comment by chandramouleswaran** [comment]
Hi,

Thanks! Glad to know that someone is finding this useful.

I understand the requirement but my questions would be why? Is there something you don't like about Unity? I have plans to explore MEF container as MEF is actually used in Visual Studio. 

On a side note, do you know of any existing libraries/apps that can provides an option for selecting the IoC? The reason behind the question is, I don't want to reinvent the wheel :)

The way I see your suggestion happening is by letting the end user create Adapters for IoC of their choice conforming to an interface - (I guess similar to IDependencyResolver as I have no experience with it, yet).

By all means, please feel free to contribute by submitting PRs if you have a solution for this.

**Comment by mmisztal1980** [comment]
Having worked with multiple IoC containers, I have to say, that I'm finding Unity lacking, my personal preference is Ninject (due to it's flexibility, fluent syntax etc.)

I'm very new to Git, so it will be a while before I'll do a PR ;) However I'd love to help out a little, so here's my implementation of a universal dependency resolver (resolves dependencies for MVC4 + MVC4 WebAPI + SignalR)

http://nx.codeplex.com/SourceControl/changeset/view/a74206655331#Nx.Web/Nx.Web/Web/UniversalDependencyResolver.cs

In the web frameworks listed above, all dependency resolution is performed via the IDependencyResolver interface, while the implementation contains a specific container ;)

**Comment by mmisztal1980** [comment]
Hi there :) any news on the topic? :)
