### ISSUE TITLE
How to theme/style the AvalonDock panes

### ISSUE THREAD

**Issue by joazlazer** [chandramouleswaran/Wide#63]
Hi @chandramouleswaran I was looking at your code and since I was trying to make an IDE similar to this, I was wanting to style AvalonDock. Unfortunately, I can't seem to find where you have done so. Any help would be appreciated. Thanks!

**Comment by joazlazer** [comment]
Oh I see >.< https://github.com/chandramouleswaran/Wide/issues/1

**Comment by chandramouleswaran** [comment]
If you are planning on making some additions, feel free to submit PRs to that repository. I am using an old version of AvalonDock but I see not reason why the theme would not work with the new one.
