### ISSUE TITLE
Bind command in View

### ISSUE THREAD

**Issue by ghost** [chandramouleswaran/Wide#64]
Hi,

how would u bind a command in view from model? :)
the following code example works but it doesnt look right...
and for much commands much worse...

in the Model (*.cs) i do the following:

```
public class TestModel : TextModel
    {
        private ICommandManager mCommandManager;

        public ICommand CMD_TEST { get { return mCommandManager.GetCommand("CMDTEST"); } }

        public TestModel(ICommandManager commandManager, IMenuService menuService)
            : base(commandManager, menuService)
        {
            mCommandManager = commandManager;
```

in the view this (*.xaml):

``````
<Controls:Tile Title="TestTile" Command="{Binding CMD_TEST}">
                <Label>Test</Label>
            </Controls:Tile>```
``````

**Comment by chandramouleswaran** [comment]
Not sure what you mean - are you saying commands need to be on the ViewModel and not Model?

**Comment by ghost** [comment]
As far as i can see, in wide the models are the viewmodels. So thats not the problem.
just wanted to know, how you would bind the commands from the ICommandManager in views.
i think there's a cleaner method than my example. :)

**Comment by ghost** [comment]
or we could bind the commands in the handler:
       `var man = _container.Resolve<ICommandManager>();
            CommandBinding test = new CommandBinding(man.GetCommand("CMDTEST"));
            view.CommandBindings.Add(test);`
