### ISSUE TITLE
PopupWindows

### ISSUE THREAD

**Issue by ghost** [chandramouleswaran/Wide#65]
i need popupmessage windows (asap :) ) ...
any plans to integrate the prism popupwindows into wide?
http://blogs.southworks.net/dcherubini/2012/05/24/popupwindowaction-using-custom-views-instead-of-windows-in-wpf-and-prism/
else i have to make a modul for that :(

**Comment by ghost** [comment]
just need to copy the folder "InteractionRequests" from the example into Wide and add the Microsoft.Expression.Interactions dependency :)

**Comment by ghost** [comment]
are u still active? O.o

**Comment by joazlazer** [comment]
Be patient >.>

**Comment by joazlazer** [comment]
Lol apparently not :P
